# Generated by Django 3.2 on 2022-10-19 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='stock',
            field=models.IntegerField(default=100),
        ),
    ]
